In [1]:
import tensorflow as tf

In [4]:
tf_zero_no = tf.zeros(4)

In [5]:
with tf.Session() as session:
    print (session.run(tf_zero_no))

[ 0.  0.  0.  0.]


In [6]:
tf_zero = tf.zeros([4])

In [7]:
with tf.Session() as session:
    print(session.run(tf_zero))

[ 0.  0.  0.  0.]


In [8]:
tf_radom = tf.random_normal([2,3])

In [10]:
with tf.Session() as session:
    print(session.run(tf_radom))

[[ 0.12864776  0.36592546 -0.7281065 ]
 [ 0.38192788  0.26384804  1.04406536]]


In [11]:
tf_truncated = tf.truncated_normal([2,3])

In [13]:
with tf.Session() as session:
    print(session.run(tf_truncated))

[[ 0.75848174 -0.62647343 -0.16356188]
 [ 0.56039464 -0.57868147  0.71338606]]


In [14]:
temp = [1,2,3,4,5]

In [15]:
temp[:2]

[1, 2]

In [16]:
temp[2:]

[3, 4, 5]